-- Доповнення живої бази nextcryptojob-jobs (registry_2026_09_14_boards). ЗГЕНЕРОВАНО з db/jobs/seed/boards.json
-- і db/jobs/seed/boards-companies-2026-09-14.json: cd engine && npx tsx scripts/jobs-seed.ts boards
-- дошки екосистем і фондів (job_boards) і роботодавці, знайдені через них, з перевіреними дошками ATS
-- Накочує controller ПІСЛЯ db/jobs/0003_job_boards.sql: wrangler d1 execute nextcryptojob-jobs --remote --file db/jobs/seed/<цей файл>
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('solana', 'Solana', 'ecosystem', 'https://jobs.solana.com/jobs', 'getro', '858', 251, 'discover', 'all', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('arbitrum', 'Arbitrum', 'ecosystem', 'https://jobs.arbitrum.io/jobs', 'getro', '4184', NULL, 'discover', 'all', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('avalanche', 'Avalanche', 'ecosystem', 'https://jobs.avax.network/jobs', 'getro', '10223', NULL, 'discover', 'all', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('monad', 'Monad', 'ecosystem', 'https://eco-jobs.monad.xyz/jobs', 'getro', '13457', NULL, 'discover', 'all', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('injective', 'Injective', 'ecosystem', 'https://injective.getro.com/jobs', 'getro', '13490', NULL, 'discover', 'all', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('cyber-fund', 'cyber.fund', 'fund', 'https://talent.cyber.fund/companies', 'getro', '9035', 47, 'discover', 'all', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('multicoin', 'Multicoin Capital', 'fund', 'https://jobs.multicoin.capital/jobs', 'getro', '390', NULL, 'discover', 'all', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('polychain', 'Polychain Capital', 'fund', 'https://jobs.polychain.capital/jobs', 'getro', '203', NULL, 'discover', 'all', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('dragonfly', 'Dragonfly', 'fund', 'https://jobs.dragonfly.xyz/jobs', 'getro', '1118', NULL, 'discover', 'all', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('electric-capital', 'Electric Capital', 'fund', 'https://jobs.electriccapital.com/jobs', 'getro', '1640', NULL, 'discover', 'all', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('coinbase-ventures', 'Coinbase Ventures', 'fund', 'https://coinbase.getro.com/jobs', 'getro', '1625', 130, 'discover', 'tagged', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API; portfolio spans non-crypto software, so only organisations Getro tags crypto or leaves untagged', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('framework', 'Framework Ventures', 'fund', 'https://jobs.framework.ventures/companies', 'getro', '1127', 63, 'discover', 'all', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('variant', 'Variant', 'fund', 'https://jobs.variant.fund/companies', 'getro', '1508', 63, 'discover', 'all', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('placeholder', 'Placeholder', 'fund', 'https://jobs.placeholder.vc/companies', 'getro', '922', 9, 'discover', 'all', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('castle-island', 'Castle Island Ventures', 'fund', 'https://jobs.castleisland.vc/companies', 'getro', '13362', 66, 'discover', 'all', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('jump-crypto', 'Jump Crypto', 'fund', 'https://jobs.jumpcrypto.com/jobs', 'getro', '20916', NULL, 'discover', 'all', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('delphi', 'Delphi Ventures', 'fund', 'https://jobs.delphiventures.io/companies', 'getro', '1440', 106, 'discover', 'all', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('spartan', 'Spartan Group', 'fund', 'https://jobs.spartangroup.io/companies', 'getro', '1179', 19, 'discover', 'all', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('animoca', 'Animoca Brands', 'fund', 'https://careers.animocabrands.com/companies', 'getro', '6230', 7, 'discover', 'all', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('blockchain-capital', 'Blockchain Capital', 'fund', 'https://jobs.blockchaincapital.com/companies', 'getro', '815', 92, 'discover', 'all', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('blockchain-association', 'Blockchain Association', 'association', 'https://jobs.theblockchainassociation.org/companies', 'getro', '869', 112, 'discover', 'tagged', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API; members include law and consulting firms, so only organisations Getro tags crypto or leaves untagged', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('outlier-ventures', 'Outlier Ventures', 'fund', 'https://jobs.outlierventures.io/companies', 'getro', '1524', 35, 'discover', 'all', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('galaxy-ventures', 'Galaxy Ventures', 'fund', 'https://venturecareers.galaxy.com/companies', 'getro', '9134', 75, 'discover', 'tagged', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API; portfolio includes fintech outside crypto, so only organisations Getro tags crypto or leaves untagged', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('bitkraft', 'Bitkraft', 'fund', 'https://careers.bitkraft.vc/jobs', 'getro', '3095', 93, 'discover', 'strict', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API; gaming fund, most portfolio is not crypto, so only organisations Getro tags crypto', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('polkadot', 'Polkadot', 'ecosystem', 'https://polkadot.getro.com/jobs', 'getro', '11180', 19, 'discover', 'all', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API; jobs.polkadot.com points at this board but answers 404', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('filecoin', 'Filecoin', 'ecosystem', 'https://careers.fil.org/jobs', 'getro', '1486', 36, 'discover', 'all', 'Getro board: weekly discovery of companies and their ATS links only (owner decision 2026-09-14, Getro terms risk accepted); jobs come from each company''s own ATS API', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('tezos', 'Tezos', 'ecosystem', 'https://careers.tezos.com', 'getro', '2502', 0, 'skip', 'all', 'Getro board is live but empty (0 companies, 0 jobs on 2026-09-14); switch to discover if it fills up', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('ethereum', 'Ethereum', 'ecosystem', NULL, 'none', NULL, NULL, 'skip', 'all', 'no ecosystem job board; ethereum.org only links third-party boards (ethereumjobboard.com, JobStash, cryptojobslist, web3.career); Ethereum Foundation already scanned via ashby:ethereum-foundation', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('optimism', 'Optimism', 'ecosystem', 'https://www.optimism.io/careers', 'ats', 'ashby:oplabs', NULL, 'skip', 'all', 'no ecosystem job board; jobs.optimism.io redirects to optimism.io/careers (OP Labs only); OP Labs and Optimism Foundation already scanned (ashby:oplabs, ashby:opfoundation)', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('base', 'Base', 'ecosystem', 'https://www.base.org/jobs', 'ats', 'greenhouse:basejobs', NULL, 'skip', 'all', 'no ecosystem job board; base.org/jobs lists the Base team only (Greenhouse board ''Base.org Careers Page'', already scanned as greenhouse:basejobs); base.getro.com is a single-company page with 0 jobs', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('polygon', 'Polygon', 'ecosystem', 'https://polygon.technology/careers', 'ats', 'ashby:polygon-labs', NULL, 'skip', 'all', 'no ecosystem job board; polygon.technology/careers reads Polygon Labs'' own Ashby board, already scanned', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('sui', 'Sui', 'ecosystem', 'https://jobs.sui.io', 'custom', NULL, NULL, 'skip', 'all', 'HireChain board (share.hirechain.io) with 9 jobs, no public API; Mysten Labs and Sui Foundation already scanned from their own Ashby boards', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('aptos', 'Aptos', 'ecosystem', 'https://aptosnetwork.com/ecosystem/jobs', 'custom', NULL, 2, 'skip', 'all', 'own page (Astro + DatoCMS, behind a Vercel checkpoint) with 10 roles from 2 companies; Aptos Labs and Aptos Foundation already scanned', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('near', 'NEAR', 'ecosystem', NULL, 'none', NULL, NULL, 'skip', 'all', 'no ecosystem job board; careers.near.org and jobs.near.org do not resolve; NEAR Foundation already scanned via greenhouse:nearfoundation', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('cosmos', 'Cosmos / Interchain', 'ecosystem', 'https://jobs.cosmos.network', 'none', NULL, NULL, 'skip', 'all', 'board dead (Cloudflare 525 on 2026-09-14); Cosmos Labs already scanned via greenhouse:cosmoslabs', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('ton', 'TON', 'ecosystem', 'https://jobs.ton.org', 'none', NULL, NULL, 'skip', 'all', 'board dead: ton.org/jobs redirects to jobs.ton.org, which does not resolve (2026-09-14); no careers link on ton.org or ton.foundation', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('starknet', 'Starknet', 'ecosystem', 'https://www.starknet.io/jobs/', 'custom', NULL, 0, 'skip', 'all', 'WordPress ''Community Jobs'' page with no listings (jobs come in through a form); Starknet Foundation already scanned via ashby:starknetfoundation', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('zksync', 'ZKsync', 'ecosystem', NULL, 'none', NULL, NULL, 'skip', 'all', 'no ecosystem job board; zksync.io/jobs is 404; Matter Labs already scanned via ashby:matter-labs', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('celestia', 'Celestia', 'ecosystem', NULL, 'none', NULL, NULL, 'skip', 'all', 'no ecosystem job board; celestia.getro.com is a single-company page with 0 jobs; Celestia Labs already scanned via lever:celestia', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('berachain', 'Berachain', 'ecosystem', 'https://careers.berachain.com', 'custom', NULL, NULL, 'skip', 'all', 'no ecosystem job board; careers.berachain.com is Berachain''s own jobs on Polymer, an ATS the scan does not read', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('sei', 'Sei', 'ecosystem', NULL, 'none', NULL, NULL, 'skip', 'all', 'no ecosystem job board; jobs.sei.io does not resolve; Sei Labs and Sei Foundation already scanned (ashby:sei-labs, ashby:seifoundation)', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('protocol-labs', 'Protocol Labs network', 'ecosystem', 'https://os.pl.xyz/jobs', 'custom', NULL, 20, 'manual', 'all', 'Protocol Labs directory (own app, not Getro or Consider): read once on 2026-09-14 (one JSON page); crypto teams whose roles link a public ATS added by hand with discovered_via ''portfolio:protocol-labs''; AI and neurotech teams left out', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('chainlink', 'Chainlink', 'ecosystem', 'https://chainlinklabs.com/open-roles', 'ats', 'ashby:chainlink-labs', NULL, 'skip', 'all', 'no ecosystem job board; chainlinklabs.com/open-roles embeds the Ashby board, but its public job API answers 404 (registry row stays disabled)', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('hedera', 'Hedera', 'ecosystem', NULL, 'none', NULL, NULL, 'skip', 'all', 'no ecosystem job board; Hashgraph already scanned via ashby:hashgraph; HBAR Inc. (Hedera Foundation) Greenhouse board added by hand', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('algorand', 'Algorand', 'ecosystem', 'https://jobs.algorand.foundation', 'none', NULL, NULL, 'skip', 'all', 'board dead: the domain still points at a Getro board that answers 404; Algorand Foundation already scanned via rippling:algorand-foundation', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('stellar', 'Stellar', 'ecosystem', NULL, 'none', NULL, NULL, 'skip', 'all', 'no ecosystem job board; stellar.getro.com is a single-company page with 0 jobs; Stellar Development Foundation already scanned via ashby:stellar', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('cardano', 'Cardano', 'ecosystem', NULL, 'none', NULL, NULL, 'skip', 'all', 'no ecosystem job board; Cardano Foundation (personio:cardano-foundation) and IOG (workable:io-global) boards added by hand; EMURGO posts on its own WordPress page', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('a16z-crypto', 'a16z crypto', 'fund', 'https://a16zcrypto.com/portfolio/', 'consider', NULL, 48, 'manual', 'all', 'Consider board: Consider terms forbid automated collection, the board is never read; portfolio companies with a public ATS added by hand from the public portfolio page a16zcrypto.com/portfolio (board: a16zcrypto.com/jobs)', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('paradigm', 'Paradigm', 'fund', 'https://www.paradigm.xyz/investments', 'consider', NULL, 57, 'manual', 'all', 'Consider board: Consider terms forbid automated collection, the board is never read; portfolio companies added by hand from paradigm.xyz/investments (board: paradigm.xyz/careers; the old Getro collection 944 still answers but no public board points to it)', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('pantera', 'Pantera Capital', 'fund', 'https://jobs.panteracapital.com/jobs', 'consider', NULL, 174, 'skip', 'all', 'Consider board: Consider terms forbid automated collection, the board is never read; panteracapital.com/portfolio renders its list with JavaScript, no company links in the page', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('hashed', 'Hashed', 'fund', 'https://www.hashed.com/portfolio/', 'consider', NULL, 159, 'manual', 'all', 'Consider board: Consider terms forbid automated collection, the board is never read; portfolio companies added by hand from hashed.com/portfolio (board: jobs.hashed.com)', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('lemniscap', 'Lemniscap', 'fund', 'https://careers.lemniscap.com/jobs', 'consider', NULL, 123, 'skip', 'all', 'Consider board: Consider terms forbid automated collection, the board is never read; lemniscap.com blocks automated requests (Cloudflare), so no portfolio page to read', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('fenbushi', 'Fenbushi Capital', 'fund', 'https://careers.fenbushicapital.vc/jobs', 'consider', NULL, 68, 'skip', 'all', 'Consider board: Consider terms forbid automated collection, the board is never read; fenbushi.vc shows only 16 featured companies; the two with a public ATS (Safe, Offchain Labs) are already scanned', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('1kx', '1kx', 'fund', 'https://1kx.capital/portfolio', 'none', NULL, 64, 'manual', 'all', 'no portfolio job board; portfolio companies with a public ATS added by hand from the public page 1kx.capital/portfolio', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('hack-vc', 'Hack VC', 'fund', 'https://www.hack.vc/portfolio', 'none', NULL, NULL, 'skip', 'all', 'no portfolio job board; hack.vc/portfolio lists names only, no company links', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('mechanism', 'Mechanism Capital', 'fund', 'https://www.mechanism.capital/portfolio', 'none', NULL, 78, 'manual', 'all', 'no portfolio job board; crypto portfolio companies with a public ATS added by hand from mechanism.capital/portfolio', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('yzi-labs', 'YZi Labs', 'fund', 'https://talent.yzilabs.com/', 'custom', NULL, 25, 'skip', 'all', 'own board (talent.yzilabs.com, Next.js app): roles are posted inside the app with no ATS links', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('robot-ventures', 'Robot Ventures', 'fund', 'https://robvc.com/', 'none', NULL, 34, 'manual', 'all', 'no portfolio job board; crypto portfolio companies with a public ATS added by hand from the homepage list at robvc.com', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('portal-ventures', 'Portal Ventures', 'fund', 'https://www.portal.vc/', 'none', NULL, 16, 'skip', 'all', 'no portfolio job board; portal.vc lists about 16 companies and none linked a public ATS of its own; portal.getro.com is a single-company page with 0 jobs', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('alliance', 'Alliance', 'fund', 'https://alliance.xyz/companies', 'none', NULL, 168, 'skip', 'all', 'no portfolio job board; alliance.xyz/companies renders its list with JavaScript; alliance.breezy.hr has Alliance''s own roles only (already scanned)', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('dwf', 'DWF Labs', 'fund', 'https://www.dwf-labs.com/ventures', 'none', NULL, NULL, 'skip', 'all', 'no portfolio job board; dwf-labs.com blocks automated requests and names no companies', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('iosg', 'IOSG Ventures', 'fund', 'https://iosg.vc/portfolio-map/', 'none', NULL, 22, 'skip', 'all', 'no portfolio job board; portfolio list is JSON inside a page script; the homepage career section is about 7 hand-picked links', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('hashkey', 'HashKey Capital', 'fund', 'https://hashkey.capital/portfolio/index.html', 'none', NULL, NULL, 'skip', 'all', 'no portfolio job board; portfolio loaded by JavaScript, no names in the page; /careers lists HashKey''s own jobs', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('okx-ventures', 'OKX Ventures', 'fund', 'https://www.okx.com/ventures', 'none', NULL, 15, 'skip', 'all', 'no portfolio job board; okx.com/ventures shows about 15 featured projects only', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO job_boards (slug, label, kind, url, platform, platform_id, companies, decision, crypto_scope, reason, checked_at) VALUES ('kraken-ventures', 'Kraken Ventures', 'fund', NULL, 'none', NULL, NULL, 'skip', 'all', 'no portfolio job board; krakenventures.com no longer resolves and kraken.com/ventures is 404; kraken.getro.com is a single-company page', '2026-09-14') ON CONFLICT(slug) DO NOTHING;
INSERT INTO companies (slug, name, ats_provider, ats_slug, enabled, discovered_via, note) VALUES
  ('3jane', '3Jane', 'lever', '3jane', 1, 'portfolio:paradigm', 'listed on the public portfolio page https://www.paradigm.xyz/investments; company site https://www.3jane.xyz/ careers page https://www.3jane.xyz/ links lever:3jane (0 open on 2026-09-14)'),
  ('alloralabs', 'Allora Labs', 'bamboohr', 'alloralabs', 1, 'portfolio:mechanism', 'listed on the public portfolio page https://www.mechanism.capital/portfolio; company site https://allora.network/ careers page https://allora.network/ links bamboohr:alloralabs (0 open on 2026-09-14)'),
  ('axiom', 'Axiom (axiom.xyz)', 'ashby', 'axiom', 1, 'portfolio:paradigm', 'listed on the public portfolio page https://www.paradigm.xyz/investments; company site https://www.axiom.xyz/ careers page https://www.axiom.xyz/ links ashby:axiom (3 open on 2026-09-14)'),
  ('bettermoney', 'The Better Money Company', 'ashby', 'bettermoney', 1, 'portfolio:a16z-crypto', 'listed on the public portfolio page https://a16zcrypto.com/portfolio/; company site https://bettermoney.com/ careers page https://bettermoney.com/ links ashby:bettermoney (6 open on 2026-09-14)'),
  ('bio', 'Bio Protocol', 'ashby', 'bio', 1, 'portfolio:protocol-labs', 'Protocol Labs network directory https://os.pl.xyz/jobs (read once on 2026-09-14) lists this team''s roles at ashby:bio (11 open on 2026-09-14)'),
  ('bluefin', 'Bluefin', 'workable', 'bluefin', 1, 'portfolio:mechanism', 'listed on the public portfolio page https://www.mechanism.capital/portfolio; company site https://bluefin.io/ careers page https://bluefin.io/careers links workable:bluefin (0 open on 2026-09-14)'),
  ('cardano-foundation', 'Cardano Foundation', 'personio', 'cardano-foundation', 1, 'curated', 'Cardano ecosystem check 2026-09-14: cardano-foundation.jobs.personio.com answers with the Cardano Foundation''s roles (1 open on 2026-09-14)'),
  ('catena', 'Catena Labs', 'ashby', 'catena', 1, 'portfolio:a16z-crypto', 'listed on the public portfolio page https://a16zcrypto.com/portfolio/; company site https://catenalabs.com/ careers page https://catenalabs.com/careers links ashby:catena (4 open on 2026-09-14)'),
  ('chainwaylabs', 'Citrea', 'bamboohr', 'chainwaylabs', 1, 'getro:9134', 'found via getro:9134 (Galaxy Ventures board, only there): its jobs link bamboohr:chainwaylabs (1 open on 2026-09-14)'),
  ('connext-network', 'Everclear (Connext)', 'lever', 'connext-network', 1, 'portfolio:hashed', 'listed on the public portfolio page https://www.hashed.com/portfolio/; company site https://www.connext.network/ careers page https://www.connext.network/ links lever:connext-network (1 open on 2026-09-14)'),
  ('cyber.fund', 'cyber•Fund', 'ashby', 'cyber.Fund', 1, 'getro:9035', 'found via getro:9035 (cyber.fund board, only there): its jobs link ashby:cyber.Fund (1 open on 2026-09-14)'),
  ('distributedcrafts', 'BOB (Build on Bitcoin)', 'workable', 'distributedcrafts', 1, 'portfolio:mechanism', 'listed on the public portfolio page https://www.mechanism.capital/portfolio; company site https://gobob.xyz/ careers page https://gobob.xyz/ links workable:distributedcrafts (0 open on 2026-09-14)'),
  ('ecoinc', 'Eco', 'greenhouse', 'ecoinc', 1, 'portfolio:a16z-crypto', 'listed on the public portfolio page https://a16zcrypto.com/portfolio/ (also 1kx); company site https://www.eco.com/ careers page https://www.eco.com/ links greenhouse:ecoinc (0 open on 2026-09-14)'),
  ('everyrealm', 'Everyrealm', 'workable', 'everyrealm', 1, 'portfolio:a16z-crypto', 'listed on the public portfolio page https://a16zcrypto.com/portfolio/ (also hashed); company site https://everyrealm.com/ careers page https://everyrealm.com/careers links workable:everyrealm (0 open on 2026-09-14)'),
  ('fence-finance', 'Fence', 'ashby', 'fence-finance', 1, 'getro:9134', 'found via getro:9134 (Galaxy Ventures board, only there): its jobs link ashby:fence-finance (4 open on 2026-09-14)'),
  ('fleek', 'Fleek', 'ashby', 'fleek', 1, 'portfolio:protocol-labs', 'Protocol Labs network directory https://os.pl.xyz/jobs (read once on 2026-09-14) lists this team''s roles at ashby:fleek (11 open on 2026-09-14)'),
  ('hadronlabs', 'Neutron', 'teamtailor', 'hadronlabs', 1, 'getro:9035', 'found via getro:9035 (cyber.fund board, also delphi): its jobs link teamtailor:hadronlabs (2 open on 2026-09-14)'),
  ('helium', 'Nova Labs (Helium)', 'greenhouse', 'helium', 1, 'portfolio:a16z-crypto', 'listed on the public portfolio page https://a16zcrypto.com/portfolio/; company site https://nova.xyz/ careers page https://nova.xyz/ links greenhouse:helium (0 open on 2026-09-14)'),
  ('impossiblecloud', 'Impossible Cloud Network', 'lever', 'impossiblecloud', 1, 'portfolio:1kx', 'listed on the public portfolio page https://1kx.capital/portfolio; company site https://www.icn.global/ careers page https://www.icn.global/careers links lever:impossiblecloud (11 open on 2026-09-14)'),
  ('incadigitalinc', 'Inca Digital', 'greenhouse', 'incadigitalinc', 1, 'getro:9134', 'found via getro:9134 (Galaxy Ventures board, only there): the company careers page https://grnh.se/2vaoaexk9us links greenhouse:incadigitalinc (11 open on 2026-09-14)')
  ON CONFLICT DO NOTHING;
INSERT INTO companies (slug, name, ats_provider, ats_slug, enabled, discovered_via, note) VALUES
  ('io-global', 'IO Global (IOG)', 'workable', 'io-global', 1, 'curated', 'Cardano ecosystem check 2026-09-14: iog.io/careers links apply.workable.com/io-global (board name ''IO Global'') (4 open on 2026-09-14)'),
  ('kiln.fi', 'Kiln', 'ashby', 'kiln.fi', 1, 'getro:869', 'found via getro:869 (Blockchain Association board, only there): the company careers page https://www.kiln.fi/careers# links ashby:kiln.fi (0 open on 2026-09-14)'),
  ('legend-xyz', 'Legend', 'ashby', 'legend-xyz', 1, 'portfolio:a16z-crypto', 'listed on the public portfolio page https://a16zcrypto.com/portfolio/; company site https://legend.xyz/ careers page https://legend.xyz/ links ashby:legend-xyz (2 open on 2026-09-14)'),
  ('liquid', 'Liquid', 'ashby', 'liquid', 1, 'portfolio:paradigm', 'listed on the public portfolio page https://www.paradigm.xyz/investments; company site https://tryliquid.xyz/ careers page https://tryliquid.xyz/ links ashby:liquid (2 open on 2026-09-14)'),
  ('o1-labs-operating-corporation', 'O(1) Labs', 'rippling', 'o1-labs-operating-corporation', 1, 'portfolio:paradigm', 'listed on the public portfolio page https://www.paradigm.xyz/investments; company site https://o1labs.org/ careers page https://o1labs.org/about-us links rippling:o1-labs-operating-corporation (0 open on 2026-09-14)'),
  ('optimum', 'Optimum', 'ashby', 'optimum', 1, 'portfolio:1kx', 'listed on the public portfolio page https://1kx.capital/portfolio; company site https://www.getoptimum.xyz/ careers page https://www.getoptimum.xyz/ links ashby:optimum (0 open on 2026-09-14)'),
  ('pixiongames', 'Pixion Games', 'teamtailor', 'pixiongames', 1, 'getro:1440', 'found via getro:1440 (Delphi Ventures board, only there): its jobs link teamtailor:pixiongames (3 open on 2026-09-14)'),
  ('pod-network', 'pod', 'ashby', 'pod-network', 1, 'portfolio:1kx', 'listed on the public portfolio page https://1kx.capital/portfolio; company site https://pod.network/ careers page https://pod.network/ links ashby:pod-network (4 open on 2026-09-14)'),
  ('puffer-finance', 'Puffer Finance', 'workable', 'puffer-finance', 1, 'portfolio:mechanism', 'listed on the public portfolio page https://www.mechanism.capital/portfolio; company site https://puffer.fi/ careers page https://puffer.fi/ links workable:puffer-finance (0 open on 2026-09-14)'),
  ('rated-roles', 'Rated Labs', 'rippling', 'rated-roles', 1, 'getro:9035', 'found via getro:9035 (cyber.fund board, only there): its jobs link rippling:rated-roles (1 open on 2026-09-14)'),
  ('solana-foundation', 'Solana Foundation', 'ashby', 'Solana%20Foundation', 1, 'getro:858', 'found via getro:858 (Solana board, also jump-crypto): its jobs link ashby:Solana%20Foundation (6 open on 2026-09-14); the same company is in the registry only with a disabled board; the same company is in the registry only with a disabled board'),
  ('sovrun', 'Sovrun', 'workable', 'sovrun', 1, 'portfolio:a16z-crypto', 'listed on the public portfolio page https://a16zcrypto.com/portfolio/ (also mechanism); company site https://www.sovrun.org/ careers page https://www.sovrun.org/ links workable:sovrun (0 open on 2026-09-14)'),
  ('sweatcoin', 'Sweatcoin', 'teamtailor', 'sweatcoin', 1, 'getro:1640', 'found via getro:1640 (Electric Capital board, only there): its jobs link teamtailor:sweatcoin (2 open on 2026-09-14)'),
  ('zircuit', 'Zircuit', 'ashby', 'Zircuit', 1, 'portfolio:robot-ventures', 'listed on the public portfolio page https://robvc.com/; company site https://www.zircuit.com/ careers page https://www.zircuit.com/ links ashby:Zircuit (0 open on 2026-09-14)')
  ON CONFLICT DO NOTHING;
INSERT OR IGNORE INTO schema_migrations(name) VALUES ('registry_2026_09_14_boards');
